[template]
  incoming-hooks = ["Shopify"]

[build]
  # This is the directory to change to before starting a build.
  publish = "public"
  # This will be your default build command
  command = "yarn build"


[template.environment]
  SHOPIFY_ACCESS_TOKEN = "Shopify Access Token"
  GATSBY_SHOPIFY_ACCESS_TOKEN = "Gatsby Shopify Access Token"
  SHOP_NAME="Store Name"
  SHOPIFY_DOMAIN="Yourshopifyname.myshopify.com"
  GATSBY_SHOPIFY_DOMAIN="Yourshopifyname.myshopify.com"
