[template]
  incoming-hooks = ["Shopify"]

[template.environment]
  SHOPIFY_ACCESS_TOKEN = "Shopify Access Token"
  GATSBY_SHOPIFY_ACCESS_TOKEN = "Gatsby Shopify Access Token"
  SHOP_NAME="hironakastore"
  SHOPIFY_DOMAIN="URL FOR SHOPIFY"
  GATSBY_SHOPIFY_DOMAIN="URL FOR SHOPIFY"
